// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM97KRbskDXP1fzvHP4gcxo2qHby1PCT8',
    appId: '1:182154926841:web:dd72fdbd9500a7e9c52028',
    messagingSenderId: '182154926841',
    projectId: 'health-recorder-93d20',
    authDomain: 'health-recorder-93d20.firebaseapp.com',
    storageBucket: 'health-recorder-93d20.appspot.com',
    measurementId: 'G-E3W8D03EVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ryh6-OYygWZUqcZc8CGtf-hjJVe5OWI',
    appId: '1:182154926841:android:cf51af6067a58094c52028',
    messagingSenderId: '182154926841',
    projectId: 'health-recorder-93d20',
    storageBucket: 'health-recorder-93d20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl81ioTzpHqyWxWPn_Y1nNiCrz0x1Bs8Q',
    appId: '1:182154926841:ios:38842ff1c2f6fdc0c52028',
    messagingSenderId: '182154926841',
    projectId: 'health-recorder-93d20',
    storageBucket: 'health-recorder-93d20.appspot.com',
    iosBundleId: 'com.example.hw1',
  );
}
